//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.Log {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Log.LogStrings", typeof(LogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 You are downloading a log file, do you want to cancel? 的本地化字符串。
        /// </summary>
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure? 的本地化字符串。
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating KML for {0} 的本地化字符串。
        /// </summary>
        public static string CreatingKmlPrompt {
            get {
                return ResourceManager.GetString("CreatingKmlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading log files to: {0} 的本地化字符串。
        /// </summary>
        public static string DownloadStarting {
            get {
                return ResourceManager.GetString("DownloadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 !!Allow 30-90 seconds for erase 的本地化字符串。
        /// </summary>
        public static string EraseComplete {
            get {
                return ResourceManager.GetString("EraseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error processing file. Make sure the file is not in use 的本地化字符串。
        /// </summary>
        public static string ErrorProcessingLogfile {
            get {
                return ResourceManager.GetString("ErrorProcessingLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetching log file {0} ... 的本地化字符串。
        /// </summary>
        public static string FetchingLog {
            get {
                return ResourceManager.GetString("FetchingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting list of log files... 的本地化字符串。
        /// </summary>
        public static string FetchingLogfileList {
            get {
                return ResourceManager.GetString("FetchingLogfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create log file directory: {0} 的本地化字符串。
        /// </summary>
        public static string LogDirectoryError {
            get {
                return ResourceManager.GetString("LogDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No logs to download 的本地化字符串。
        /// </summary>
        public static string NoLogsFound {
            get {
                return ResourceManager.GetString("NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect your drone 的本地化字符串。
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select some logs by checking the check boxes in the list 的本地化字符串。
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing {0} 的本地化字符串。
        /// </summary>
        public static string ProcessingLog {
            get {
                return ResourceManager.GetString("ProcessingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found {0} log files, note: item sizes are just an estimate. 的本地化字符串。
        /// </summary>
        public static string SomeLogsFound {
            get {
                return ResourceManager.GetString("SomeLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: 的本地化字符串。
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
